import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import useTranslation from "next-translate/useTranslation";
import PageWrapper from "@/components/PageWrapper";

export default function ProductPage() {
  const { t } = useTranslation("common");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <div className="home-wrapper">
          <p>product page</p>
        </div>
      </PageWrapper>
    </>
  );
}
