import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import useTranslation from "next-translate/useTranslation";
import PageWrapper from "@/components/PageWrapper";

export default function Home() {
  const { t } = useTranslation("common");
  return (
    <>
      <Head>
        <title>Industrial Green</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <div className="home-wrapper">
          <Image src="/home.png" width="600" height="1000" alt="flowers" />
          <div className="text-container">
            <h1>
              Industrial <span className="green">Green</span>
            </h1>
            <motion.div
              initial={{ opacity: 0, y: 0 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 0 }}
              transition={{ duration: 0.8, delay: 0.8 }}
            >
              <h4>{t("homeTitle")}</h4>
              <p className="subtitle">{t("homeSubtitle")}</p>
              <Link href="/products">
                <button className="button button-text">
                  {t("homeButton")}
                </button>
              </Link>
              <main className="about-us">
                <div>
                  <h4>{t("aboutUs")}</h4>
                </div>
                <p>{t("aboutUsContent")}</p>
              </main>
            </motion.div>
          </div>
        </div>
      </PageWrapper>
    </>
  );
}
