import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import useTranslation from 'next-translate/useTranslation'
import PageWrapper from "@/components/PageWrapper";

export default function Home() {
  const {t} = useTranslation('common')
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <h1>home</h1>
        <h2>{t('contact')}</h2>
      </PageWrapper>
    </>
  );
}
